# Generated by Django 6.0.1 on 2026-01-28 07:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(help_text='Complete raw response from LLM API')),
                ('caller', models.CharField(help_text='File and function where call_llm was invoked', max_length=500)),
                ('model', models.CharField(help_text='LLM model used', max_length=100)),
                ('reasoning_effort', models.CharField(default='low', help_text='Reasoning effort level', max_length=20)),
                ('system_instructions', models.TextField(blank=True, help_text='System instructions sent to LLM', null=True)),
                ('user_prompt', models.TextField(blank=True, help_text='User prompt sent to LLM', null=True)),
                ('json_schema', models.JSONField(blank=True, help_text='JSON schema used for structured output', null=True)),
                ('schema_name', models.CharField(blank=True, help_text='Name of the schema used', max_length=100, null=True)),
                ('parsed_json', models.JSONField(blank=True, help_text='Parsed JSON data from structured output', null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Number of input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Number of output tokens')),
                ('cached_tokens', models.PositiveIntegerField(default=0, help_text='Number of cached input tokens')),
                ('reasoning_tokens', models.PositiveIntegerField(default=0, help_text='Number of reasoning tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total tokens used')),
                ('succeeded', models.BooleanField(default=True, help_text='Whether the LLM call succeeded')),
                ('llm_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost of this LLM call in USD', max_digits=10)),
                ('response_time_seconds', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Call Log',
                'verbose_name_plural': 'LLM Call Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year (e.g., 2025)')),
                ('month', models.PositiveIntegerField(help_text='Month (1-12)')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Total LLM cost in USD for this month', max_digits=10)),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total tokens used this month')),
                ('total_calls', models.PositiveIntegerField(default=0, help_text='Total LLM calls made this month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user this usage record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Monthly Usage',
                'verbose_name_plural': 'User Monthly Usage',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='llm_service_user_id_056b45_idx'), models.Index(fields=['year', 'month'], name='llm_service_year_f4ea3a_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
