# Generated by Django 6.0.1 on 2026-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='chat_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
