# Generated by Django for call log admin improvements

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcalllog",
            name="user_message_preview",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="llmcalllog",
            name="raw_response_payload",
            field=models.TextField(blank=True),
        ),
    ]
